app/User.php
<?php

namespace Novedades52;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'api_token',
    ];

    public function experiences()
    {
        return $this->hasMany(Experience::class);
    }

    public function getNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function scopeSearch($q, $value)
    {
        $q->when($value, function ($q) use ($value) {
            return $q->where('email', $value);
        });
    }

    public function isAdmin()
    {
        return $this->role == 'admin';
    }

    public function isCollaborator()
    {
        return ! ($this->role == 'admin');
    }
}

resources/views/admin/loginas.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">

                @if(Session::has('error'))
                    <div class="alert alert-danger">
                        {{ Session::get('error') }}
                    </div>
                @endif

                <div class="panel panel-default">

                    <div class="panel-heading">Login as</div>

                    <div class="panel-body">
                        Login as users

                        <ul>
                            @foreach($users as $user)
                                <li>
                                    {{ $user->name }} - <a href="/admin/login-as/{{ $user->id }}">Login as</a>
                                </li>
                            @endforeach
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Users</div>

                    <div id="content" class="panel-body">
                        <table class="table">
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td><a href="#">Edit</a></td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection