app/User.php
<?php

namespace Novedades52;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'api_token',
    ];

    public function experiences()
    {
        return $this->hasMany(Experience::class);
    }

    public function getNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function scopeSearch($q, $value)
    {
        $q->when($value, function ($q) use ($value) {
            return $q->where('email', $value);
        });
    }

    public function isAdmin()
    {
        return $this->role == 'admin';
    }

    public function isCollaborator()
    {
        return ! ($this->role == 'admin');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace Novedades52\Http\Controllers\Admin;

use Illuminate\Http\Request;

use Novedades52\Http\Controllers\Controller;
use Novedades52\Http\Requests;
use Novedades52\User;

class UserController extends Controller
{
    public function index(Request $request)
    {
        /*
        $users = User::search($request->search)
            ->withCount(['experiences' => function ($q) {
                $q->where('name', 'PHP');
            }])
            ->inRandomOrder()
            ->get();
*/
        $users = User::whereColumn('first_name', 'last_name')
            ->get();

        return view('admin.users.index', compact('users'));
    }

    public function edit(User $user)
    {
        abort_unless($user->isCollaborator(), 404, 'No se puede editar un administrador');

        return view('admin.users.edit', compact('user'));
    }

    public function update(User $user, Request $request)
    {
        abort_if($user->isAdmin(), 404, 'El usuario es adminsitrador y no puede ser editado');
        $this->validate($request, [
            'email' => 'required',
        ]);
        $user->fill($request->all());
        $user->save();

        return back()->with('success', true);
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">

                @include('partials/errors')

                @if (session('success'))
                    <p class="alert alert-success">¡Usuario actualizado!</p>
                @endif

                <div class="panel panel-default">
                    <div class="panel-heading">Editar usuario</div>

                    <div class="panel-body" id="content">
                        <form action="{{ route('admin.users.update', $user) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}

                            <div class="form-group">
                                <label for="email">E-mail:</label>
                                <input type="email" name="email" value="{{ old('email', $user->email) }}"
                                       class="form-control">
                            </div>

                            <button type="submit" class="btn btn-primary">Actualizar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Users</div>

                    <div class="panel-body" id="content">

                        <form class="form form-inline" action="{{ route('admin.users.index') }}" method="GET">
                            <input type="text" name="search" placeholder="Search users by email"
                                   class="form-control" value="{{request('search', '')}}">
                            <button type="submit" class="btn btn-primary">Search</button>
                        </form>

                        <br>

                        <table class="table">
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->experiences_count }}</td>
                                    <td><a href="{{ route('admin.users.edit', ['user' => $user->id]) }}">Editar</a></td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection